Repository asyed03/EduConnect-CSC301, pull requests merged in 2024-02, with the labels that each got.

#5 Sprint 1: Database setup basis
  backend/databasemanager.py
  backend/requestmanager.py
  backend/requirements.txt
  backend/schema.ddl
  backend/server.py
  backend/user.py
Labels: Feature

#8 Sprint 1: Connect login and registration to the database and provide error messages in the UI
  backend/databasemanager.py
  backend/requestmanager.py
  frontend/src/App.css
  frontend/src/routes/login.jsx
  frontend/src/routes/register.jsx
Labels: Feature

#9 Sprint 1: Added starter code for announcements frontend and backend
  backend/announcement.py
  backend/databasemanager.py
  backend/requestmanager.py
  backend/schema.ddl
  backend/server.py
  frontend/src/main.jsx
  frontend/src/routes/announcements.jsx
  frontend/src/styles/Announcements.scss
Labels: Feature

#13 Polishing and connecting all features
  backend/databasemanager.py
  backend/group.py
  backend/package-lock.json
  backend/package.json
  backend/requestmanager.py
  backend/schema.ddl
  backend/server.py
  backend/server_announcements.py
  backend/server_group.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/components/announcementhighlight.jsx
  frontend/src/components/course_highlight.jsx
  frontend/src/components/coursehighlight.jsx
  frontend/src/components/left_menu.jsx
  frontend/src/components/menu.jsx
  frontend/src/components/upcoming_event_highlight.jsx
  frontend/src/components/upcomingeventhighlight.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/routes/announcements.jsx
  frontend/src/routes/course-view.jsx
  frontend/src/routes/dashboard.jsx
  frontend/src/routes/groupregister.jsx
  frontend/src/routes/index.jsx
  frontend/src/routes/login.jsx
  frontend/src/routes/postannouncement.jsx
  frontend/src/routes/register.jsx
  frontend/src/styles/AnnouncementHighlight.scss
  frontend/src/styles/Announcements.scss
  frontend/src/styles/CourseHighlight.scss
  frontend/src/styles/CourseView.scss
  frontend/src/styles/Dashboard.scss
  frontend/src/styles/LeftMenu.scss
  frontend/src/styles/Menu.css
  frontend/src/styles/Menu.scss
  frontend/src/styles/UpcomingEventHighlight.scss
  frontend/src/styles/course-view.css
  frontend/src/styles/course_highlight.css
  frontend/src/styles/dashboard.css
  frontend/src/styles/groupregister.scss
  frontend/src/styles/left_menu.css
  frontend/src/styles/upcoming_event_highlight.css
Labels: enhancement, Feature

#14 Sprint 1: Final touches and profile settings
  backend/databasemanager.py
  backend/event.py
  backend/requestmanager.py
  backend/schema.ddl
  backend/server.py
  frontend/src/App.css
  frontend/src/components/menu.jsx
  frontend/src/components/upcomingeventhighlight.jsx
  frontend/src/main.jsx
  frontend/src/routes/course-view.jsx
  frontend/src/routes/dashboard.jsx
  frontend/src/routes/postannouncement.jsx
  frontend/src/routes/postevent.jsx
  frontend/src/routes/profilesettings.jsx
  frontend/src/styles/Login.scss
  frontend/src/styles/ProfileSettings.scss
  frontend/src/styles/Register.scss
  frontend/src/styles/UpcomingEventHighlight.scss
Labels: enhancement, Feature

#15 Sprint 2: Updating email and password settings
  backend/databasemanager.py
  backend/requestmanager.py
  backend/server.py
  frontend/src/routes/groupregister.jsx
  frontend/src/routes/profilesettings.jsx
Labels: Feature

#16 Sprint 2: Separate request managers
  backend/databasemanager.py
  backend/requestmanager.py
  backend/requestmanagers/announcementrequestmanager.py
  backend/requestmanagers/eventrequestmanager.py
  backend/requestmanagers/grouprequestmanager.py
  backend/requestmanagers/requestmanager.py
  backend/requestmanagers/userrequestmanager.py
  backend/server.py
Labels: enhancement

#17 Sprint 2: Front End Group Messages Design
  frontend/src/main.jsx
  frontend/src/routes/messages.jsx
  frontend/src/styles/messages.scss
Labels: Feature

#20 Sprint 2: Changing Username
  backend/databasemanager.py
  backend/requestmanagers/userrequestmanager.py
  frontend/src/routes/profilesettings.jsx
  frontend/src/routes/register.jsx
  frontend/src/styles/ProfileSettings.scss
Labels: Feature

#19 Sprint 2: announcement-interactions (2.3)
  backend/comment.py
  backend/databasemanager.py
  backend/requestmanagers/announcementcommentrequestmanager.py
  backend/requestmanagers/announcementrequestmanager.py
  backend/schema.ddl
  backend/server.py
  frontend/src/components/announcementhighlight.jsx
  frontend/src/components/commenthighlight.jsx
  frontend/src/routes/course-view.jsx
  frontend/src/styles/AnnouncementHighlight.scss
Labels: Feature

#18 Sprint 2: Chatroom backend implementation (2.1)
  backend/databasemanager.py
  backend/messaging/chateventmanager.py
  backend/messaging/chatserver.py
  backend/requestmanagers/internalrequestmanager.py
  backend/requestmanagers/userrequestmanager.py
  backend/requirements.txt
  backend/schema.ddl
  backend/server.py
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/messages.jsx
  frontend/src/socket.js
  frontend/src/styles/messages.scss
Labels: Feature
